version: '3'
services:
  web:
    build: .
    container_name: baileyapp
    volumes:
      - .:/baileyapp
    ports:
      - "8000:8000"
    command: >
      bash -c "python manage.py makemigrations &&
               python manage.py migrate &&
               python manage.py runserver"
