# Generated by Django 4.2.5 on 2023-10-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50, unique=True)),
                ('google_url', models.URLField(default='www.google.com')),
                ('intl_country_code', models.CharField(max_length=2)),
                ('country_code', models.CharField(max_length=3)),
                ('valid_country', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookPageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('page_link', models.URLField(blank=True, null=True)),
                ('source', models.CharField(default='search', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_text', models.TextField()),
                ('additional_info', models.TextField()),
            ],
            options={
                'db_table': 'message_templates',
            },
        ),
        migrations.CreateModel(
            name='MessangerPrimary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('messenger_link', models.URLField(unique=True)),
                ('source', models.CharField(default='search', max_length=20)),
                ('message', models.TextField()),
                ('message_status', models.CharField(default='Default', max_length=20)),
                ('status', models.CharField(default='ready', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OpenAIAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'openai_api_keys',
            },
        ),
        migrations.CreateModel(
            name='PrimaryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_type', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_source', models.CharField(default='search', max_length=20)),
                ('website', models.URLField(blank=True, max_length=150, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='ready', max_length=50)),
                ('message_status', models.CharField(default='Default', max_length=20)),
            ],
            options={
                'db_table': 'primarycontact',
            },
        ),
        migrations.CreateModel(
            name='SerpAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serp_api_key', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'serp_api_keys',
            },
        ),
        migrations.CreateModel(
            name='WebPageTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, null=True)),
                ('website_link', models.URLField(blank=True, null=True)),
                ('page_link', models.URLField(blank=True, null=True)),
                ('Sub_Heading', models.JSONField()),
            ],
        ),
    ]
