# Generated by Django 4.2.5 on 2023-10-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChromeUserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chrome_user_path', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'chrome_user_path',
            },
        ),
    ]
